### ISSUE TITLE
Upgrade extJS 4.2 to 7.x

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online-Frontend#18]
Use extJS Upgrade advisor. https://www.sencha.com/products/extjs/upgradeadviser/
Upgrade in several steps to respective next major version ([GPL versions](https://github.com/Edirom/Edirom-Online-Frontend/issues/18))

- [ ] Edirom/Edirom-Online-Frontend#17
- [ ] Edirom/Edirom-Online-Frontend#14
- [ ] Upgrade extJS 6.2 to 7.x #435
